logger:
  enable: true
  pretty_backtrace: true
  level: debug
  format: compact

server:
  binding: 0.0.0.0
  port: 3000

database:
  uri: postgres://rustok:rustok@localhost:5432/rustok_dev
  enable_logging: true
  min_connections: 1
  max_connections: 10
  auto_migrate: true

auth:
  jwt:
    secret: dev-secret-change-in-production-min-32-chars!!
    expiration: 604800
