[package]
name = "leptos-zustand"
version.workspace = true
edition.workspace = true
license.workspace = true

description = "Minimal internal store helpers for Leptos frontends"

[dependencies]
serde = { workspace = true, features = ["derive"] }
