[package]
name = "rustok-admin"
version.workspace = true
edition.workspace = true

[dependencies]
leptos = { workspace = true, features = ["csr"] }
leptos_router = { workspace = true, features = ["csr"] }
