[package]
name = "leptos-table"
version.workspace = true
edition.workspace = true
license.workspace = true

description = "Minimal internal table helpers for Leptos frontends"

[dependencies]
serde = { workspace = true, features = ["derive"] }
